### Create a new Todo
POST http://localhost:8080/todos
Content-Type: application/json

{
  "title": "Learn Spring Boot",
  "completed": false
}


### Get all Todos
GET http://localhost:8080/todos


### Update Todo
PUT http://localhost:8080/todos/1
Content-Type: application/json

{
  "title": "Learn Spring Boot",
  "completed": true
}


### Delete Todo
DELETE http://localhost:8080/todos/1


### Get all Todos after delete
GET http://localhost:8080/todos


### Not Found test
PUT http://localhost:8080/todos/999
Content-Type: application/json

{
  "title": "Test Todo",
  "completed": true
}

